/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package pj_sonde.View;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import pj_sonde.Controler.C_Batiment;

/**
 *
 * @author kevin
 */
public class V_A_Batiment extends javax.swing.JDialog {

    /**
     * Creates new form V_A_Batiment
     */
    private C_Batiment gestionBatiment;

    public V_A_Batiment(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public void aff_A_Batiment(C_Batiment gestionBatiment) {
        this.gestionBatiment = gestionBatiment;
        this.setTitle("Ajout d'un bâtiments");
        this.setSize(1080, 720);
        this.setLocationRelativeTo(null);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_titre = new javax.swing.JLabel();
        lb_code = new javax.swing.JLabel();
        lb_libelle = new javax.swing.JLabel();
        lb_commentaire = new javax.swing.JLabel();
        sp_commentaire = new javax.swing.JScrollPane();
        ta_commentaire = new javax.swing.JTextArea();
        ftf_code = new javax.swing.JFormattedTextField();
        ftf_libelle = new javax.swing.JFormattedTextField();
        btn_cancel = new javax.swing.JButton();
        btn_add = new javax.swing.JButton();
        mb_menu = new javax.swing.JMenuBar();
        mn_fichier = new javax.swing.JMenu();
        mi_fermer = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lb_titre.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lb_titre.setText("Ajout d'un bâtiment");

        lb_code.setText("Code du bâtiment  : ");

        lb_libelle.setText("Libelle du bâtiment :");

        lb_commentaire.setText("Commentaire : ");

        ta_commentaire.setColumns(20);
        ta_commentaire.setRows(5);
        sp_commentaire.setViewportView(ta_commentaire);

        btn_cancel.setText("Annuler");
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });

        btn_add.setText("Ajouter");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });

        mn_fichier.setText("Fichier");

        mi_fermer.setText("Fermer");
        mi_fermer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_fermerActionPerformed(evt);
            }
        });
        mn_fichier.add(mi_fermer);

        mb_menu.add(mn_fichier);

        setJMenuBar(mb_menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(328, 328, 328)
                        .addComponent(lb_titre))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lb_code)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ftf_code, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lb_libelle)
                                    .addComponent(lb_commentaire))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sp_commentaire)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(ftf_libelle, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(329, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lb_titre)
                .addGap(120, 120, 120)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_code)
                    .addComponent(ftf_code, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_libelle)
                    .addComponent(ftf_libelle, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_commentaire)
                    .addComponent(sp_commentaire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(281, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mi_fermerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_fermerActionPerformed
        setVisible(false);
    }//GEN-LAST:event_mi_fermerActionPerformed

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        String code, libelle, commentaire;

        // Vérification des champs obligatoires
        JTextField[] champs = {ftf_code, ftf_libelle};

        for (JTextField champ : champs) {
            if (champ.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Veuillez remplir tous les champs", "Erreur", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }

        // Vérification des longueurs
        if (ftf_libelle.getText().length() > 50) {
            JOptionPane.showMessageDialog(this, "Le libellé doit contenir moins de 50 caractères", "Erreur", JOptionPane.ERROR_MESSAGE);
            return;
        }
        libelle = ftf_libelle.getText();

        if (ftf_code.getText().length() > 50) {
            JOptionPane.showMessageDialog(this, "Le code doit contenir moins de 50 caractères", "Erreur", JOptionPane.ERROR_MESSAGE);
            return;
        }
        code = ftf_code.getText();

        // Si commentaire renseigné, vérification de la longueur
        if (ta_commentaire.getText().length() > 250) {
            JOptionPane.showMessageDialog(this, "Le commentaire doit contenir moins de 250 caractères", "Erreur", JOptionPane.ERROR_MESSAGE);
            return;
        }
        commentaire = ta_commentaire.getText().isEmpty() ? null : ta_commentaire.getText(); //Soit on recupère le commentaire soit on met à null

        // Vérification si le bâtiments existe 
        try {
            if (gestionBatiment.batimentExiste(code, libelle)) {
                JOptionPane.showMessageDialog(this, "Le code ou le libelle est déjà utilisé", "Erreur", JOptionPane.ERROR_MESSAGE);
                return;
            }
        } catch (Exception ex) {
            Logger.getLogger(V_A_Batiment.class.getName()).log(Level.SEVERE, null, ex);
        }

        // Enregistrement en DB
        try {
            gestionBatiment.add_Batiment(code, libelle, commentaire);
            JOptionPane.showMessageDialog(this, "Le bâtiment " + code + " a bien été ajouté", "Confirmation", JOptionPane.INFORMATION_MESSAGE);
            ftf_code.setText("");
            ftf_libelle.setText("");
            ta_commentaire.setText("");
            setVisible(false);
        } catch (Exception ex) {
            Logger.getLogger(V_A_Batiment.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btn_addActionPerformed

    private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed
        int result = JOptionPane.showConfirmDialog(this, "Êtes vous sûr de vouloir d'annuler votre saisie ?", "Confirmation annulation", JOptionPane.YES_NO_OPTION);
        if (result == JOptionPane.YES_OPTION) {
            ftf_code.setText("");
            ftf_libelle.setText("");
            ta_commentaire.setText("");
            setVisible(false);
        }
    }//GEN-LAST:event_btn_cancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(V_A_Batiment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(V_A_Batiment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(V_A_Batiment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(V_A_Batiment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                V_A_Batiment dialog = new V_A_Batiment(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_cancel;
    private javax.swing.JFormattedTextField ftf_code;
    private javax.swing.JFormattedTextField ftf_libelle;
    private javax.swing.JLabel lb_code;
    private javax.swing.JLabel lb_commentaire;
    private javax.swing.JLabel lb_libelle;
    private javax.swing.JLabel lb_titre;
    private javax.swing.JMenuBar mb_menu;
    private javax.swing.JMenuItem mi_fermer;
    private javax.swing.JMenu mn_fichier;
    private javax.swing.JScrollPane sp_commentaire;
    private javax.swing.JTextArea ta_commentaire;
    // End of variables declaration//GEN-END:variables
}
