/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package pj_sonde.View;

import at.favre.lib.crypto.bcrypt.BCrypt;
import java.util.LinkedHashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import pj_sonde.Controler.C_Utilisateur;
import pj_sonde.Model.M_Role;

/**
 *
 * @author kevin
 */
public class V_A_Utilisateur extends javax.swing.JDialog {

    /**
     * Creates new form V_A_Utilisateur
     */
    private C_Utilisateur gestionUtilisateur;
    private M_Role unRole;
    private LinkedHashMap<Integer, M_Role> lesRoles;

    public V_A_Utilisateur(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public void aff_A_Utilisateur(C_Utilisateur gestionUtilisateur, LinkedHashMap<Integer, M_Role> lesRoles) {
        this.gestionUtilisateur = gestionUtilisateur;
        this.lesRoles = lesRoles;
        this.setTitle("Ajout d'un bâtiments");
        this.setSize(1080, 720);
        this.setLocationRelativeTo(null);

        for (Integer uneCle : lesRoles.keySet()) {
            unRole = lesRoles.get(uneCle);
            cb_role.addItem(unRole.getNom());
        }

        setVisible(true);
    }

    private int getIdByNom(String codeNom) {
        int res = -1;
        for (M_Role role : lesRoles.values()) {
            if (role.getNom().equals(codeNom)) {
                res = role.getId();
            }
        }
        return res;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_titre = new javax.swing.JLabel();
        ln_name = new javax.swing.JLabel();
        ln_email = new javax.swing.JLabel();
        lb_commentaire = new javax.swing.JLabel();
        sp_commentaire = new javax.swing.JScrollPane();
        ta_commentaire = new javax.swing.JTextArea();
        ftf_name = new javax.swing.JFormattedTextField();
        ftf_email = new javax.swing.JFormattedTextField();
        btn_cancel = new javax.swing.JButton();
        btn_add = new javax.swing.JButton();
        lb_mdp = new javax.swing.JLabel();
        ftf_password = new javax.swing.JFormattedTextField();
        lb_role = new javax.swing.JLabel();
        cb_role = new javax.swing.JComboBox<>();
        ftf_password_confirm = new javax.swing.JFormattedTextField();
        lb_mdp1 = new javax.swing.JLabel();
        mb_menu = new javax.swing.JMenuBar();
        mn_fichier = new javax.swing.JMenu();
        mi_fermer = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        lb_titre.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lb_titre.setText("Ajout d'un utilisateur");

        ln_name.setText("Nom de l'utilisateur :");

        ln_email.setText("Email de l'utilisateur :");

        lb_commentaire.setText("Commentaire : ");

        ta_commentaire.setColumns(20);
        ta_commentaire.setRows(5);
        sp_commentaire.setViewportView(ta_commentaire);

        btn_cancel.setText("Annuler");
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });

        btn_add.setText("Ajouter");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });

        lb_mdp.setText("Mot de passe de l'utilisateur :");

        lb_role.setText("Role :");

        lb_mdp1.setText("Confirmer le mot de passe :");

        mn_fichier.setText("Fichier");

        mi_fermer.setText("Fermer");
        mi_fermer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_fermerActionPerformed(evt);
            }
        });
        mn_fichier.add(mi_fermer);

        mb_menu.add(mn_fichier);

        setJMenuBar(mb_menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ln_email)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ftf_email, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ln_name)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ftf_name, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lb_mdp)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ftf_password, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lb_role)
                                        .addComponent(lb_commentaire))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cb_role, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(39, 39, 39)
                                    .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btn_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGap(85, 85, 85)
                                    .addComponent(sp_commentaire, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lb_mdp1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ftf_password_confirm, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(328, 328, 328)
                        .addComponent(lb_titre)))
                .addGap(222, 310, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lb_titre)
                .addGap(120, 120, 120)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ln_name)
                    .addComponent(ftf_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ln_email)
                    .addComponent(ftf_email, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_mdp)
                    .addComponent(ftf_password, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ftf_password_confirm, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_mdp1))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_role, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_role))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sp_commentaire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_commentaire))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(193, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mi_fermerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_fermerActionPerformed
        int result = JOptionPane.showConfirmDialog(this, "Êtes vous sûr de vouloir d'annuler votre saisie ?", "Confirmation annulation", JOptionPane.YES_NO_OPTION);
        if (result == JOptionPane.YES_OPTION) {
            ftf_name.setText("");
            ftf_email.setText("");
            ta_commentaire.setText("");
            ftf_password.setText("");
            ftf_password_confirm.setText("");
            setVisible(false);
        }
    }//GEN-LAST:event_mi_fermerActionPerformed

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        String name, email, password, commentaire;
        int idRole;
        // Vérification des champs obligatoires
        JTextField[] champs = {ftf_name, ftf_email, ftf_password};

        for (JTextField champ : champs) {
            if (champ.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Veuillez remplir tous les champs", "Erreur", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }

        // Vérification des longueurs
        if (ftf_email.getText().length() > 255) {
            JOptionPane.showMessageDialog(this, "Le nom doit contenir moins de 255 caractères", "Erreur", JOptionPane.ERROR_MESSAGE);
            return;
        }
        email = ftf_email.getText();

        if (ftf_name.getText().length() > 255) {
            JOptionPane.showMessageDialog(this, "Le code doit contenir moins de 255 caractères", "Erreur", JOptionPane.ERROR_MESSAGE);
            return;
        }
        name = ftf_name.getText();

        if (ftf_password.getText().length() > 255) {
            JOptionPane.showMessageDialog(this, "Le code doit contenir moins de 255 caractères", "Erreur", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (!(ftf_password.getText().equals(ftf_password_confirm.getText()))) {
            JOptionPane.showMessageDialog(this, "Les deux mots de passe ne correspondent pas", "Erreur", JOptionPane.ERROR_MESSAGE);
            return;
        }
        password = BCrypt.withDefaults().hashToString(12, ftf_password.getText().toCharArray());

        // Si commentaire renseigné, vérification de la longueur
        if (ta_commentaire.getText().length() > 250) {
            JOptionPane.showMessageDialog(this, "Le commentaire doit contenir moins de 250 caractères", "Erreur", JOptionPane.ERROR_MESSAGE);
            return;
        }
        commentaire = ta_commentaire.getText().isEmpty() ? null : ta_commentaire.getText(); //Soit on recupère le commentaire soit on met à null

        // Vérification si le bâtiments existe 
        try {
            if (gestionUtilisateur.utilisateurExiste(email)) {
                JOptionPane.showMessageDialog(this, "L'email est déjà utilisé", "Erreur", JOptionPane.ERROR_MESSAGE);
                return;
            }
        } catch (Exception ex) {
            Logger.getLogger(V_A_Utilisateur.class.getName()).log(Level.SEVERE, null, ex);
        }
        idRole = getIdByNom((String) cb_role.getSelectedItem());

        // Enregistrement en DB
        try {
            gestionUtilisateur.add_Utilisateur(name, email, password, commentaire, idRole);
            JOptionPane.showMessageDialog(this, "L'utilisateur " + name + " a bien été ajouté", "Confirmation", JOptionPane.INFORMATION_MESSAGE);
            ftf_name.setText("");
            ftf_email.setText("");
            ta_commentaire.setText("");
            setVisible(false);
        } catch (Exception ex) {
            Logger.getLogger(V_A_Utilisateur.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btn_addActionPerformed

    private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed
        int result = JOptionPane.showConfirmDialog(this, "Êtes vous sûr de vouloir d'annuler votre saisie ?", "Confirmation annulation", JOptionPane.YES_NO_OPTION);
        if (result == JOptionPane.YES_OPTION) {
            ftf_name.setText("");
            ftf_email.setText("");
            ta_commentaire.setText("");
            ftf_password.setText("");
            ftf_password_confirm.setText("");
            setVisible(false);
        }
    }//GEN-LAST:event_btn_cancelActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        int result = JOptionPane.showConfirmDialog(this, "Êtes vous sûr de vouloir d'annuler votre saisie ?", "Confirmation annulation", JOptionPane.YES_NO_OPTION);
        if (result == JOptionPane.YES_OPTION) {
            ftf_name.setText("");
            ftf_email.setText("");
            ta_commentaire.setText("");
            ftf_password.setText("");
            ftf_password_confirm.setText("");
            setVisible(false);
        }
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(V_A_Utilisateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(V_A_Utilisateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(V_A_Utilisateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(V_A_Utilisateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                V_A_Utilisateur dialog = new V_A_Utilisateur(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_cancel;
    private javax.swing.JComboBox<String> cb_role;
    private javax.swing.JFormattedTextField ftf_email;
    private javax.swing.JFormattedTextField ftf_name;
    private javax.swing.JFormattedTextField ftf_password;
    private javax.swing.JFormattedTextField ftf_password_confirm;
    private javax.swing.JLabel lb_commentaire;
    private javax.swing.JLabel lb_mdp;
    private javax.swing.JLabel lb_mdp1;
    private javax.swing.JLabel lb_role;
    private javax.swing.JLabel lb_titre;
    private javax.swing.JLabel ln_email;
    private javax.swing.JLabel ln_name;
    private javax.swing.JMenuBar mb_menu;
    private javax.swing.JMenuItem mi_fermer;
    private javax.swing.JMenu mn_fichier;
    private javax.swing.JScrollPane sp_commentaire;
    private javax.swing.JTextArea ta_commentaire;
    // End of variables declaration//GEN-END:variables
}
