/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package pj_sonde.View;

import java.sql.SQLException;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.LinkedHashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import pj_sonde.Controler.C_Sonde;
import pj_sonde.Model.M_Batiment;
import pj_sonde.Model.M_Salle;
import pj_sonde.Model.M_Sonde;
import pj_sonde.Model.M_Type;
import pj_sonde.Model.M_Unite;

/**
 *
 * @author kevin
 */
public class V_A_Sonde extends javax.swing.JDialog {

    private C_Sonde gestionSonde;
    private M_Sonde uneSonde;
    private M_Batiment unBatiment;
    private M_Salle uneSalle;
    private M_Type unType;
    private M_Unite uneUnite;

    private LinkedHashMap<Integer, M_Batiment> lesBatiments;
    private LinkedHashMap<Integer, M_Salle> lesSalles;
    private LinkedHashMap<String, M_Unite> lesUnites;
    private LinkedHashMap<Integer, M_Type> lesTypes;

    public V_A_Sonde(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public void aff_A_Sonde(C_Sonde gestionSonde,
            LinkedHashMap<Integer, M_Batiment> lesbatiments,
            LinkedHashMap<Integer, M_Salle> lesSalles,
            LinkedHashMap<String, M_Unite> lesUnites,
            LinkedHashMap<Integer, M_Type> lesTypes) {
        this.gestionSonde = gestionSonde;
        this.lesBatiments = lesbatiments;
        this.lesSalles = lesSalles;
        this.lesUnites = lesUnites;
        this.lesTypes = lesTypes;
        this.setTitle("Ajout d'une sonde");
        this.setSize(1080, 720);
        this.setLocationRelativeTo(null);

        for (Integer uneCle : lesTypes.keySet()) {
            unType = lesTypes.get(uneCle);
            cb_type.addItem(unType.getLibelle());
        }
        for (String uneCle : lesUnites.keySet()) {
            uneUnite = lesUnites.get(uneCle);
            cb_unite.addItem(uneUnite.getLibelle());
        }

        setVisible(true);
    }

    private int getIdByCode(String libelleType) {
        int res = -1;
        for (M_Type type : lesTypes.values()) {
            if (type.getLibelle().equals(libelleType)) {
                res = type.getId();
            }
        }
        return res;
    }

    private String getCodeByLibelle(String libelleUnite) {
        String res = "";
        for (M_Unite unite : lesUnites.values()) {
            if (unite.getLibelle().equals(libelleUnite)) {
                res = unite.getCode();
            }
        }
        return res;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_titre = new javax.swing.JLabel();
        lb_code = new javax.swing.JLabel();
        lb_nom = new javax.swing.JLabel();
        lb_commentaire = new javax.swing.JLabel();
        sp_commentaire = new javax.swing.JScrollPane();
        ta_commentaire = new javax.swing.JTextArea();
        ftf_code = new javax.swing.JFormattedTextField();
        ftf_ip = new javax.swing.JFormattedTextField();
        btn_cancel = new javax.swing.JButton();
        btn_add = new javax.swing.JButton();
        lb_ip = new javax.swing.JLabel();
        ftf_nom = new javax.swing.JFormattedTextField();
        lb_mac = new javax.swing.JLabel();
        lb_date_achat = new javax.swing.JLabel();
        ftf_mac = new javax.swing.JFormattedTextField();
        cb_type = new javax.swing.JComboBox<>();
        lb_type = new javax.swing.JLabel();
        cb_unite = new javax.swing.JComboBox<>();
        lb_libelle3 = new javax.swing.JLabel();
        dc_achat = new com.toedter.calendar.JDateChooser();
        mb_menu = new javax.swing.JMenuBar();
        mn_fichier = new javax.swing.JMenu();
        mi_fermer = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lb_titre.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lb_titre.setText("Ajout d'une sonde");

        lb_code.setText("Code de la sonde :");

        lb_nom.setText("Nom de la salle :");

        lb_commentaire.setText("Commentaire : ");

        ta_commentaire.setColumns(20);
        ta_commentaire.setRows(5);
        sp_commentaire.setViewportView(ta_commentaire);

        btn_cancel.setText("Annuler");

        btn_add.setText("Ajouter");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });

        lb_ip.setText("Adresse IP : ");

        lb_mac.setText("Adresse MAC :");

        lb_date_achat.setText("Date d'achat :");

        lb_type.setText("Type de sonde :");

        lb_libelle3.setText("Unité de la sonde :");

        mn_fichier.setText("Fichier");

        mi_fermer.setText("Fermer");
        mi_fermer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_fermerActionPerformed(evt);
            }
        });
        mn_fichier.add(mi_fermer);

        mb_menu.add(mn_fichier);

        setJMenuBar(mb_menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(218, 218, 218)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lb_nom)
                                    .addComponent(lb_commentaire)
                                    .addComponent(lb_code)
                                    .addComponent(lb_ip)
                                    .addComponent(lb_mac))
                                .addGap(21, 21, 21))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lb_date_achat)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sp_commentaire, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(cb_unite, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cb_type, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ftf_mac, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(dc_achat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ftf_code, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(ftf_ip, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE)
                                .addComponent(ftf_nom, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(328, 328, 328)
                        .addComponent(lb_titre)))
                .addGap(0, 220, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(207, 207, 207)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lb_libelle3)
                    .addComponent(lb_type))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lb_titre)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_code)
                    .addComponent(ftf_code, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_nom)
                    .addComponent(ftf_nom, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_ip)
                    .addComponent(ftf_ip, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ftf_mac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_mac))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dc_achat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_date_achat))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_type))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_unite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_libelle3))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_commentaire)
                    .addComponent(sp_commentaire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(293, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mi_fermerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_fermerActionPerformed
        setVisible(false);
    }//GEN-LAST:event_mi_fermerActionPerformed

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        String code, nom, mac, ip, codeUnite, commentaire;
        int idType;
        String rexIp = "^(?:(?:25[0-5]|2[0-4]\\d|1?\\d{1,2})(?:\\.(?!$)|$)){4}$";
        String rexMac = "^(?:[0-9A-Fa-f]{2}([:-]))(?:[0-9A-Fa-f]{2}\\1){4}[0-9A-Fa-f]{2}$";
        JTextField[] champs = {ftf_code, ftf_ip, ftf_mac, ftf_nom};

        for (JTextField champ : champs) {
            if (champ.getText().isEmpty() || champ.getText().isBlank()) {
                JOptionPane.showMessageDialog(this, "Veuillez remplir tous les champs", "Erreur", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
        if (ftf_code.getText().length() > 50) {
            JOptionPane.showMessageDialog(this, "Le code doit contenir moins de 50 caractères", "Erreur", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (ftf_nom.getText().length() > 150) {
            JOptionPane.showMessageDialog(this, "Le nom doit contenir moins de 50 caractères", "Erreur", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (ftf_ip.getText().length() > 50) {
            JOptionPane.showMessageDialog(this, "L'adresse IP doit contenir moins de 50 caractères", "Erreur", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (!ftf_ip.getText().matches(rexIp)) {
            JOptionPane.showMessageDialog(this, "L'adresse IP doit être au format X.X.X.X (exemple : 192.168.1.1)", "Erreur", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (ftf_mac.getText().length() > 50) {
            JOptionPane.showMessageDialog(this, "L'adresse mac doit contenir moins de 50 caractères", "Erreur", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (!ftf_mac.getText().matches(rexMac)) {
            JOptionPane.showMessageDialog(this, "L'adresse mac doit être dans le bon format", "Erreur", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (ta_commentaire.getText().length() > 250) {
            JOptionPane.showMessageDialog(this, "Le commentaire doit contenir moins de 250 caractères", "Erreur", JOptionPane.ERROR_MESSAGE);
            return;
        }
        LocalDate dateAchat = dc_achat.getDate()
                .toInstant()
                .atZone(ZoneId.systemDefault())
                .toLocalDate();

        //if(dateAchat.is)
        code = ftf_code.getText();
        nom = ftf_nom.getText();
        ip = ftf_ip.getText();
        mac = ftf_mac.getText();

        idType = getIdByCode((String) cb_type.getSelectedItem());
        codeUnite = getCodeByLibelle((String) cb_unite.getSelectedItem());

//        System.out.println(idType);
//        System.out.println(codeUnite);
        commentaire = ta_commentaire.getText().isEmpty() ? null : ta_commentaire.getText();
        try {
            gestionSonde.add_Sonde(code, nom, ip, mac, LocalDate.EPOCH, commentaire, idType, codeUnite);
        } catch (SQLException ex) {
            Logger.getLogger(V_A_Sonde.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_addActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(V_A_Sonde.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(V_A_Sonde.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(V_A_Sonde.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(V_A_Sonde.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                V_A_Sonde dialog = new V_A_Sonde(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_cancel;
    private javax.swing.JComboBox<String> cb_type;
    private javax.swing.JComboBox<String> cb_unite;
    private com.toedter.calendar.JDateChooser dc_achat;
    private javax.swing.JFormattedTextField ftf_code;
    private javax.swing.JFormattedTextField ftf_ip;
    private javax.swing.JFormattedTextField ftf_mac;
    private javax.swing.JFormattedTextField ftf_nom;
    private javax.swing.JLabel lb_code;
    private javax.swing.JLabel lb_commentaire;
    private javax.swing.JLabel lb_date_achat;
    private javax.swing.JLabel lb_ip;
    private javax.swing.JLabel lb_libelle3;
    private javax.swing.JLabel lb_mac;
    private javax.swing.JLabel lb_nom;
    private javax.swing.JLabel lb_titre;
    private javax.swing.JLabel lb_type;
    private javax.swing.JMenuBar mb_menu;
    private javax.swing.JMenuItem mi_fermer;
    private javax.swing.JMenu mn_fichier;
    private javax.swing.JScrollPane sp_commentaire;
    private javax.swing.JTextArea ta_commentaire;
    // End of variables declaration//GEN-END:variables
}
