/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pj_sonde;

import java.sql.SQLException;
import pj_sonde.Model.*;
import pj_sonde.View.*;

import java.util.LinkedHashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import pj_sonde.Controler.C_Sonde;
import pj_sonde.Controler.C_Sonde;
import pj_sonde.C_Main;
import pj_sonde.Controler.C_Batiment;

/**
 *
 * @author kevin
 */
public class V_Main extends javax.swing.JFrame {

    private V_CMS_Sonde frm_CMS_Sonde;
    private C_Main gestionProjet;
    private C_Sonde gestionSondes;
    private C_Batiment gestionBatiment;
    private M_Sonde uneSonde;
    LinkedHashMap<Integer, M_Sonde> lesSondes;
    Integer uneCle;

    public V_Main(C_Main gestionProjetSonde) {
        this.gestionProjet = gestionProjetSonde;
        initComponents();
    }

    public void afficher(C_Sonde gestionSondes, C_Batiment gestionBatiment) {
        this.gestionBatiment = gestionBatiment;
        this.gestionSondes = gestionSondes;
        this.setTitle("Gestion des sondes & bâtiments ");
        this.setSize(1080, 720);
        this.setLocationRelativeTo(null);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mb_menu = new javax.swing.JMenuBar();
        mn_fichier = new javax.swing.JMenu();
        mi_quitter = new javax.swing.JMenuItem();
        mn_sonde = new javax.swing.JMenu();
        mi_consult_sonde = new javax.swing.JMenuItem();
        mi_ajout_sonde = new javax.swing.JMenuItem();
        mn_batiment = new javax.swing.JMenu();
        mi_consult_bat = new javax.swing.JMenuItem();
        mi_ajout_bat = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        mn_fichier.setText("Fichier");

        mi_quitter.setText("Quitter");
        mi_quitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_quitterActionPerformed(evt);
            }
        });
        mn_fichier.add(mi_quitter);

        mb_menu.add(mn_fichier);

        mn_sonde.setText("Sonde");

        mi_consult_sonde.setText("Consultation Sonde");
        mi_consult_sonde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_consult_sondeActionPerformed(evt);
            }
        });
        mn_sonde.add(mi_consult_sonde);

        mi_ajout_sonde.setText("Ajout sonde");
        mn_sonde.add(mi_ajout_sonde);

        mb_menu.add(mn_sonde);

        mn_batiment.setText("Bâtiment");

        mi_consult_bat.setText("Consultation bâtiments");
        mi_consult_bat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_consult_batActionPerformed(evt);
            }
        });
        mn_batiment.add(mi_consult_bat);

        mi_ajout_bat.setText("Ajout bâtiment");
        mi_ajout_bat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_ajout_batActionPerformed(evt);
            }
        });
        mn_batiment.add(mi_ajout_bat);

        mb_menu.add(mn_batiment);

        setJMenuBar(mb_menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mi_quitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_quitterActionPerformed
        gestionProjet.close();
        System.exit(0);
    }//GEN-LAST:event_mi_quitterActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        gestionProjet.close();
    }//GEN-LAST:event_formWindowClosing

    private void mi_consult_sondeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_consult_sondeActionPerformed
        try {
            gestionSondes.aff_CMS_Sonde();
        } catch (SQLException ex) {
            Logger.getLogger(V_Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mi_consult_sondeActionPerformed

    private void mi_consult_batActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_consult_batActionPerformed
        try {
            gestionBatiment.aff_CMS_Batiment();
        } catch (Exception ex) {
            Logger.getLogger(V_Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mi_consult_batActionPerformed

    private void mi_ajout_batActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_ajout_batActionPerformed
        try {
            gestionBatiment.aff_A_Batiment();
        } catch (Exception ex) {
            Logger.getLogger(V_Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mi_ajout_batActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(V_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(V_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(V_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(V_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new V_Main(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar mb_menu;
    private javax.swing.JMenuItem mi_ajout_bat;
    private javax.swing.JMenuItem mi_ajout_sonde;
    private javax.swing.JMenuItem mi_consult_bat;
    private javax.swing.JMenuItem mi_consult_sonde;
    private javax.swing.JMenuItem mi_quitter;
    private javax.swing.JMenu mn_batiment;
    private javax.swing.JMenu mn_fichier;
    private javax.swing.JMenu mn_sonde;
    // End of variables declaration//GEN-END:variables
}
